// setters
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_USERS = "SET_USERS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_CATEGORY = "SET_CATEGORY";

// getters
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_USERS = "GET_USERS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_CATEGORY = "GET_CATEGORY";

// errors
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";

export const ADD_TO_FAVORITES = "ADD_FAVORITE";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const SAVE_USER_INFO = "SAVE_USER_INFO";
