export const FETCH_USERS_ACTIVE = "FETCH_USERS_ACTIVE";
export const FETCH_USERS_DEACTIVATE = "FETCH_USERS_DEACTIVATE";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

// setters
export const SET_PRODUCTS = "SET_PRODUCTS";

// getters
export const GET_PRODUCTS = "GET_PRODUCTS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
