// setters
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_BY_ID = "SET_PRODUCT_BY_ID";
export const SET_TRANSACTION = "SET_TRANSACTION";
export const SET_USERS = "SET_USERS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_TRANSACTION_BY_ID = "SET_TRANSACTION_BY_ID";
export const SET_TRANSACTION_BY_USER_EMAIL = "SET_TRANSACTION_BY_USER_EMAIL";
export const SET_USER_DETAIL = "SET_USER_DETAIL";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CATEGORY_BY_ID = "SET_CATEGORY_BY_ID";
export const SET_INQUIRIES = "SET_INQUIRIES";
export const SET_TRANSACTION_LOADING = "TRANSACTION/SET_TRANSACTION_LOADING";
// getters
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_USERS = "GET_USERS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTION = "GET_TRANSACTION";
export const GET_TRANSACTION_BY_ID = "GET_TRANSACTION_BY_ID";
export const GET_TRANSACTION_BY_USER_EMAIL = "GET_TRANSACTION_BY_USER_EMAIL";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const GET_INQUIRIES = "GET_INQUIRIES";

// errors
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";
export const FETCH_TRANSACTIONS_ERROR = "FETCH_TRANSACTIONS_ERROR";
export const FETCH_PRODUCT_BY_ID_ERROR = "FETCH_PRODUCT_BY_ID_ERROR";

export const SAVE_USER_INFO = "SAVE_USER_INFO";

export const SET_APP_LOADING = "APP/SET_APP_LOADING";
export const SET_APP_AUTH = "APP/SET_APP_AUTH";
export const INIT_APP = "APP/INIT_APP";
export const DELETE_USER_SESSION = "USER/DELETE_USER_SESSION";
